name: ContextManager
main: me.asofold.bukkit.contextmanager.ContextManager
version: 0.11.2
depend:
- PluginLibSharedLibrary
- PermissionsEx
softdepend:
- mcMMO
- WorldGuard
- ChestShop
commands:
  cmreload:
    description: reload settings
  mute:
    description: 'Mute a player, if desired for a certain amount of minutes.'
    usage: '/mute <player> [<minutes>]'
    aliases:
    - cmmute
  unmute:
    description: 'Remove a player from muted.'
    usage: '/unmute <player>'
    aliases:
    - cmunmute
    - demute
  muted:
    description: 'Show muted players.'
    usage: '/muted'
    aliases:
    - cmmuted
  context:
    description: 'Set your chat context.'
    aliases:
    - cx
    usage: '/context ... or /cx ... for: | /cx channel <name> | /cx greedy ... | /cx recipients <rec1> ... | /cx ignore <player1> ... | /cx reset [ignore|all|recipients] | /cx info | /cx services | /cx find ... |/cx history | Use - (-) as prefix to remove an entry!'
  cxc:
    description: 'Show or select channel.'
    aliases:
    - cxch
  cxr:
    description: 'Show or select recipients.'
    aliases:
    - cxrec
  cxign:
    description: 'Show or add ignored players.'
  cxinf:
    description: 'Show context info.'
  cxcl:
    description: 'Reset context.'
  cxfind:
    description: 'Find stuff.'
    aliases:
    - cxfin
    - cxfi
    - cxf

